### ISSUE TITLE
0.3.9 Ubuntu Bug Report: "SyntaxError: Unexpected token"

### ISSUE THREAD

**Issue by hykilpikonna** [KillWolfVlad/GitKraken-Pro-AUR#11]
The JS on 0.3.9 couldn't run. It works on my Windows and MacOS desktops but not on Ubuntu.
The version 0.3.8 is working fine, and there's more happening in the yarn install log for 0.3.8 than the log for 0.3.9. Maybe that's the problem?

Screenshots: [https://imgur.com/a/6Yx0cDG](url)

Version: 0.3.9
System: Ubuntu 17.10.

0.3.9 Yarn Install Output:

		hykilpikonna@ubuntu:~/Desktop/temp/tem/GitCracken$ sudo yarn install
		yarn install v1.6.0
		[1/4] Resolving packages...
		[2/4] Fetching packages...
		[3/4] Linking dependencies...
		[4/4] Building fresh packages...
		$ rimraf dist && tsc
		Done in 4.10s.
		
0.3.9 Log:

		hykilpikonna@ubuntu:~/Desktop/temp/tem/GitCracken$ sudo node dist/bin/gitcracken.js patcher auto
		/home/hykilpikonna/Desktop/temp/tem/GitCracken/dist/bin/gitcracken-patcher.js:65
		(async () => {
			   ^

		SyntaxError: Unexpected token (
			at createScript (vm.js:56:10)
			at Object.runInThisContext (vm.js:97:10)
			at Module._compile (module.js:542:28)
			at Object.Module._extensions..js (module.js:579:10)
			at Module.load (module.js:487:32)
			at tryModuleLoad (module.js:446:12)
			at Function.Module._load (module.js:438:3)
			at Module.runMain (module.js:604:10)
			at run (bootstrap_node.js:383:7)
			at startup (bootstrap_node.js:149:9)

0.3.8 Yarn Install Output (which worked fine):

		hykilpikonna@ubuntu:~/Desktop/temp/t2/GitCracken$ sudo yarn install
		yarn install v1.6.0
		[1/4] Resolving packages...
		[2/4] Fetching packages...
		[3/4] Linking dependencies...
		[4/4] Building fresh packages...
		$ rimraf dist && gulp
		[#############################################################---------------------------------------------] 542/940[13:46:05] Using gulpfile ~/Desktop/temp/t2/GitCracken/gulpfile.js
		[13:46:05] Starting 'bin'...
		[13:46:05] Starting 'src'...
		[13:46:05] Starting 'package.json'...
		[13:46:05] Finished 'package.json' after 69 ms
		[13:46:10] Finished 'src' after 4.96 s
		[13:46:10] Finished 'bin' after 5.39 s
		[13:46:10] Starting 'default'...
		[13:46:10] Finished 'default' after 5.55 μs
		Done in 24.37s.

0.3.8 Log:

		hykilpikonna@ubuntu:~/Desktop/temp/t2/GitCracken$ sudo node dist/bin/gitcracken.js patcher auto
																					   
		• Description: GitKraken utils for non-commercial use
		• Version: 0.3.8
		• Author: KillWolfVlad
		• License: GPL-3.0
		• Home Page: https://github.com/KillWolfVlad/GitKraken-Pro-AUR

		==> 📦 Backup /usr/share/gitkraken/resources/app.asar ➔ /usr/share/gitkraken/resources/app.asar.1524948376868.backup
		==> 🔓 Unpack /usr/share/gitkraken/resources/app.asar ➔ /usr/share/gitkraken/resources/app
		==> 🔨 Patch /usr/share/gitkraken/resources/app with pro feature
		==> 🔒 Pack /usr/share/gitkraken/resources/app ➔ /usr/share/gitkraken/resources/app.asar
		==> 🔥 Remove /usr/share/gitkraken/resources/app
		==> 👌 Patching done!

**Comment by KillWolfVlad** [comment]
Hello @hykilpikonna!

What nodejs version on your Windows, macOS and Ubuntu? I think on your Ubuntu nodejs v6 (from official repo). But on on Windows and macOS nodejs is newer.

GitCracken [works well](https://github.com/KillWolfVlad/GitKraken-Pro-AUR/issues/3#issuecomment-311297120) with nodejs v7 or later. If your nodejs is too old, just install latest v8 or v10 version :smile:

**Comment by hykilpikonna** [comment]
Thanks, it did work after I upgraded my nodejs to v8.

> What nodejs version on your Windows, macOS and Ubuntu?

MacOS and Windows: v10.0.0
Ubuntu: Was v6.11.4, now v8.11.1

I thought my nodejs was the newest when apt told me it is the newest...

		hykilpikonna@ubuntu:~$ sudo apt-get upgrade nodejs
		Reading package lists... Done
		Building dependency tree       
		Reading state information... Done
		nodejs is already the newest version (6.11.4~dfsg-1ubuntu1).

**Comment by KillWolfVlad** [comment]
> I thought my nodejs was the newest when apt told me it is the newest...

This is strange. Can you paste `node --version` output?

**Comment by hykilpikonna** [comment]
I had to upgrade to v8 with [this tutorial](https://nodesource.com/blog/installing-node-js-8-tutorial-linux-via-package-manager/).

> Can you paste node --version output?

Before upgrade:

		hykilpikonna@ubuntu:~$ node -v
		v6.11.4

After upgrade:

		hykilpikonna@ubuntu:~/Desktop/temp/t9$ node -v
		v8.11.1

**Comment by KillWolfVlad** [comment]
Maybe you should start from scratch? Delete all GitCracken files and try again.

**Comment by KillWolfVlad** [comment]
And try install nodejs 10 on Ubuntu.

**Comment by hykilpikonna** [comment]
> Maybe you should start from scratch? Delete all GitCracken files and try again.

It is working already after I upgraded my nodejs to v8, thanks ;)

**Comment by KillWolfVlad** [comment]
Happy to help.

P.S. Not good at English.
