### ISSUE TITLE
Normal bash script?

### ISSUE THREAD

**Issue by CRCinAU** [KillWolfVlad/GitKraken-Pro-AUR#3]
Have you thought about making a stand-alone bash script to do this work as well?

Would be interesting to make this available for non-arch users...

**Comment by KillWolfVlad** [comment]
use [gitkraken-pro.sh](https://github.com/KillWolfVlad/GitKraken-Pro-AUR/blob/master-pro/gitkraken-pro.sh)

Read [README](https://github.com/KillWolfVlad/GitKraken-Pro-AUR#readme) for get more information

**Comment by CRCinAU** [comment]
For what its worth, on Fedora, you need to install:

node-gyp
libXext-devel
libXScrnSaver-devel

The dependency tree should pull everything else that is required in....

**Comment by CRCinAU** [comment]
I also note one issue:

`gitcracken-17ZX1Are/GitCracken/bin/gitcracken-pack.js:33
async function autoPacking() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)`

**Comment by KillWolfVlad** [comment]
@CRCinAU what nodejs and npm version are you using?

```bash
node --version
npm --version
```

**Comment by CRCinAU** [comment]
$ node --version
v6.10.3
$ npm --version
3.10.10

**Comment by KillWolfVlad** [comment]
> only nodejs >= v7.* support `async function` without `babel`

try install nodejs v7.* or v8.*

**Comment by CRCinAU** [comment]
Ok, so for testing from scratch, I added a few things....

As root:
```
# dnf erase nodejs npm
# dnf install https://rpm.nodesource.com/pub_8.x/fc/26/x86_64/nodesource-release-fc26-1.noarch.rpm
# dnf install nodejs
# dnf install bsdtar node-gyp libcurl-devel libgnome-keyring-devel libXext-devel libXScrnSaver-devel openssl-devel
```
As a normal user:
```
$ git clone https://github.com/KillWolfVlad/GitKraken-Pro-AUR.git
$ cg GitKraken-Pro-AUR
$ sh ./gitkracken-pro.sh
```

All seems to work well.

**Comment by KillWolfVlad** [comment]
`gitkraken-pro.sh` has been dropped. All rebuild code was been moved to `PKGBUILD`

**Comment by CRCinAU** [comment]
Any hints on how non-arch users can use this now?

**Comment by KillWolfVlad** [comment]
From `README`

> Other Linux distributions (third-party installation script + [Patcher](https://github.com/KillWolfVlad/GitKraken-Pro-AUR/blob/master-pro/README.md#gitcracken-aka-patcher))

Are you using `Fedora` right? `GitKraken` perfect works on `Fedora 27` in `VirtualBox`, just follow [official instructions](https://support.gitkraken.com/how-to-install)

**Comment by CRCinAU** [comment]
Ok, for reference, it seems to be a little more complex... I managed to get it working with the following. It assumes that you have install gitkracken in ~/bin/gitkracken and your repo is checked out to ~/git/GitKraken-Pro-AUR

```
cd ~/bin/gitkraken/
source ~/git/GitKraken-Pro-AUR/PKGBUILD
wget -O "gitcracken-${_gitcrackenver}.tar.xz.txt" "https://pastebin.com/raw/${_gitcrackenver}"
base64 -d "gitcracken-${_gitcrackenver}.tar.xz.txt" > gitcracken-${_gitcrackenver}.tar.xz
tar -Jxf "gitcracken-${_gitcrackenver}.tar.xz"
pushd GitCracken
npm i
popd
node "GitCracken/bin/gitcracken.js" patcher auto --asar "resources/app.asar" --asar-dir "resources/app"

## Cleaning up.
rm -fR GitCracken
rm -f "gitcracken-${_gitcrackenver}.tar.xz.txt" "gitcracken-${_gitcrackenver}.tar.xz"
rm -fR "resources/app.asar.unpacked" resources/*.backup
```

**Comment by KillWolfVlad** [comment]
Great! But in ideally should be a `makepkg` port to any distro

**Comment by KillWolfVlad** [comment]
It is difficult to maintain other operating systems, e.g. Fedora. Maybe in the future, but not now.
