### ISSUE TITLE
Can't run the aplication after patch

### ISSUE THREAD

**Issue by lburbanoulloa** [KillWolfVlad/GitKraken-Pro-AUR#4]
Enviroment:
Windows10 x64, GitKraken 3.1.1 64bits, Node version 8.2.1

Patch launched in a command terminal, with administrator privileges. The patch was runned in autopatching mode and pro feature, with success. After this, the file pathced size is larger than original.
app.asar (patched file) -> 196.035 Kb
app.asar (original  file) -> 143.224 Kb

When GitKraken is launched, it shows the loading screen, but never pass it.

Any idea?

**Comment by KillWolfVlad** [comment]
Hi @lburbanoulloa!

I have the same issue from `GitKraken` v3.x.x AFAIK

 `GitKraken` doesn't work well with patched `app.asar` file (I think it is `electron` issue)

You should unpack `app.asar` file into `resources` directory

You can do it via `node bin\gitcracken.js patcher unpack` command or use [asar](https://github.com/electron/asar) (`GitCracken` use it)

After update to new version you can delete old `app` directory from `%UserName%\AppData\Local\gitkraken`

**Comment by lburbanoulloa** [comment]
Yesss!!

Thank you very much!!

------ Mensaje original ------
De: "KillWolfVlad" <notifications@github.com>
Para: "KillWolfVlad/GitKraken-Pro-AUR" 
<GitKraken-Pro-AUR@noreply.github.com>
CC: "Luis" <lburbanoulloa@gmail.com>; "Mention" 
<mention@noreply.github.com>
Enviado: 10/10/2017 21:32:29
Asunto: Re: [KillWolfVlad/GitKraken-Pro-AUR] Can't run the aplication 
after patch (#4)

**Comment by KillWolfVlad** [comment]
I disable packing `app.asar` in `GitCracken aka Patcher` in autopatching mode on `Windows`

@lburbanoulloa can you test [GitCracken v0.3.4 aka Patcher](https://pastebin.com/qhyGseBB) and `GitKraken` v3.1.2 (everything should work)?

**Comment by dalisoft** [comment]
@KillWolfVlad 
```bash
node bin\gitcracken.js patcher unpack
```
did the trick, GitKraken was launched, but where i know it's now PRO, as in bottom anyway shows 0 day trial

**Comment by KillWolfVlad** [comment]
Hi @dalisoft!

Can you answer some questions?

- GitCracken aka Patcher version
- GitKraken version
- Node.js version
- yarn version
- macOS version
- Did you follow GitCracken aka Patcher README?

> WARNING! On macOS you should patch GitKraken only after first launch and full program closing!

**Comment by KillWolfVlad** [comment]
P.S. If you know Russian, you can use it)))

**Comment by dalisoft** [comment]
Hello @KillWolfVlad 
- GitCracken v0.3.9
- GitKraken v3.5.1
- Node v9.11.1
- Yarn v1.5.1
- macOS 10.13.2
- Few days ago see README, but today can't find it

How i can remove GitKraken fully and reinstall (i have DMG)?

Thanks for amazing crack, i see you worked hard on it :)

**Comment by KillWolfVlad** [comment]
> Thanks for amazing crack, i see you worked hard on it :)

Thank you)))

> How i can remove GitKraken fully and reinstall (i have DMG)?

Yes, lets try with reinstalling!

- Delete GitKraken (as normal macOS application) from `Applications`
- Delete all configs from `~/.gitkraken/` and `~/.config/GitKraken/`
- Install GitKraken again using official installer
- Run GitKraken after installation
- QUIT FROM GITKRAKEN (cmd+Q)! IT IS IMPORTANT!
- Patch using this command `node dist/bin/gitcracken.js patcher`
- Run GitKraken
- Register new account
- Enjoy!

P.S. You should have internet connection to activate GitKraken.

**Comment by dalisoft** [comment]
Thanks for guide,
`node dist/bin/gitcracken.js patcher unpack` only worked for patch.
Registered and verified new account. At bottom right shows FREE, it is ok and i can use PRO features?

**Comment by KillWolfVlad** [comment]
> node dist/bin/gitcracken.js patcher unpack only worked for patch.

What about `node dist/bin/gitcracken.js patcher` command? Can you paste output?

> At bottom right shows FREE, it is ok and i can use PRO features?

99% did not. But if you can create new profile and switch between them - all fine!

I don't have real macOS for additional tests. I will try reproduce your issue in VMware Workstation soon.

**Comment by dalisoft** [comment]
I still cannot switch between user.
No errors, but infinite splash screen shows GitKraken

**Comment by KillWolfVlad** [comment]
> No errors, but infinite splash screen shows GitKraken

Same problem on Windows :laughing: Maybe it is same issues.

Can you do all [steps](https://github.com/KillWolfVlad/GitKraken-Pro-AUR/issues/4#issuecomment-381338631) again, but use this command to patch?

```bash
node dist/bin/gitcracken.js patcher unpack patch
```

**Comment by dalisoft** [comment]
Thank you, patching second time helper and it works on macOS, shows PRO and can change between User. Great work and thanks again for amazing help =)

**Comment by KillWolfVlad** [comment]
HOORAY!!!

I close this issue and open new about infinite splash screen.

**Comment by dalisoft** [comment]
Yea, great work. Thank you =)
