### ISSUE TITLE
Error during node-gyp rebuild

### ISSUE THREAD

**Issue by akhamar** [KillWolfVlad/GitKraken-Pro-AUR#5]
On any of both gitkraken-pro-deb.sh or gitkraken-pro.sh
Launch as root on debian 8 and 9

npm --version
5.4.2

node --version
v8.7.0

> node-gyp rebuild

make: Entering directory '/home/xxxxxx/build/GitKraken-Pro-AUR-master-pro/src-deb/gitkraken-modules-3.1.2/node_modules/@paulcbetts/system-idle-time/build'
  CXX(target) Release/obj.target/system_idle_time/src/module.o
  CXX(target) Release/obj.target/system_idle_time/src/linux/idle.o
  SOLINK_MODULE(target) Release/obj.target/system_idle_time.node
  COPY Release/system_idle_time.node
make: Leaving directory '/home/xxxxxx/build/GitKraken-Pro-AUR-master-pro/src-deb/gitkraken-modules-3.1.2/node_modules/@paulcbetts/system-idle-time/build'
npm WARN saveError ENOENT: no such file or directory, open '/home/xxxxxx/build/GitKraken-Pro-AUR-master-pro/src-deb/gitkraken-modules-3.1.2/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/xxxxxx/build/GitKraken-Pro-AUR-master-pro/src-deb/gitkraken-modules-3.1.2/package.json'
npm WARN gitkraken-modules-3.1.2 No description
npm WARN gitkraken-modules-3.1.2 No repository field.
npm WARN gitkraken-modules-3.1.2 No README data
npm WARN gitkraken-modules-3.1.2 No license field.

+ @paulcbetts/system-idle-time@1.0.4
added 3 packages in 1.75s
module.js:529
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/node-gyp/lib/node-gyp.js:12:10)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)

**Comment by KillWolfVlad** [comment]
I'm not sure, but does your path contains spaces? If it is true, go to nodejs/node-gyp#65

**Comment by akhamar** [comment]
My path doesn't contain space. I did try as a "normal" user, no change.

> git clone https://github.com/KillWolfVlad/GitKraken-Pro-AUR.git
> cd GitKraken-Pro-AUR
> chmod 750 *.sh
> ./gitkraken-pro.sh

...

==> Unpack /tmp/GitKraken-Pro-AUR/gitkraken-3.1.2/gitkraken/resources/app.asar into /tmp/GitKraken-Pro-AUR/gitkraken-3.1.2/gitkraken/resources/app-enterprise
==> Unpacking done!

██████╗  █████╗ ████████╗ ██████╗██╗  ██╗███████╗██████╗ 
██╔══██╗██╔══██╗╚══██╔══╝██╔════╝██║  ██║██╔════╝██╔══██╗
██████╔╝███████║   ██║   ██║     ███████║█████╗  ██████╔╝
██╔═══╝ ██╔══██║   ██║   ██║     ██╔══██║██╔══╝  ██╔══██╗
██║     ██║  ██║   ██║   ╚██████╗██║  ██║███████╗██║  ██║
╚═╝     ╚═╝  ╚═╝   ╚═╝    ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
                                                         
• Description: GitKraken utils for non-commercial use
• Version: 0.3.4
• Author: KillWolfVlad
• License: GPL-3.0
• Home Page: https://github.com/KillWolfVlad/GitKraken-Pro-AUR

==> Patch /tmp/GitKraken-Pro-AUR/gitkraken-3.1.2/gitkraken/resources/app-enterprise with enterprise feature
==> Patching done!

> @paulcbetts/system-idle-time@1.0.4 install /tmp/GitKraken-Pro-AUR/gitkraken-modules-3.1.2/node_modules/@paulcbetts/system-idle-time
> node-gyp rebuild

make : on entre dans le répertoire « /tmp/GitKraken-Pro-AUR/gitkraken-modules-3.1.2/node_modules/@paulcbetts/system-idle-time/build »
  CXX(target) Release/obj.target/system_idle_time/src/module.o
  CXX(target) Release/obj.target/system_idle_time/src/linux/idle.o
  SOLINK_MODULE(target) Release/obj.target/system_idle_time.node
  COPY Release/system_idle_time.node
make : on quitte le répertoire « /tmp/GitKraken-Pro-AUR/gitkraken-modules-3.1.2/node_modules/@paulcbetts/system-idle-time/build »
/tmp/GitKraken-Pro-AUR/gitkraken-modules-3.1.2
└─┬ @paulcbetts/system-idle-time@1.0.4 
  ├── bindings@1.2.1 
  └── nan@2.7.0 

npm WARN enoent ENOENT: no such file or directory, open '/tmp/GitKraken-Pro-AUR/gitkraken-modules-3.1.2/package.json'
npm WARN gitkraken-modules-3.1.2 No description
npm WARN gitkraken-modules-3.1.2 No repository field.
npm WARN gitkraken-modules-3.1.2 No README data
npm WARN gitkraken-modules-3.1.2 No license field.
module.js:471
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/node-gyp/lib/node-gyp.js:12:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by KillWolfVlad** [comment]
Looks like `npm` installation problem. Debian does not provide `npm` as official package. Try reinstall `npm`.

**Comment by akhamar** [comment]
nodejs provide a repo for debian. I can't tell for sure but I believe npm and node are working okey on debian (98% chances it's okey)
I can try with ubuntu, later today

**Comment by KillWolfVlad** [comment]
Also you can install official [package](https://www.gitkraken.com/download/linux-deb) and apply [GitCracken aka Patcher](https://pastebin.com/qhyGseBB) (the earthiest way to get GitKraken, but I want to solve this issue)

**Comment by paulogdm** [comment]
Also having the same issue here... (Hi again Wolf)

**Comment by KillWolfVlad** [comment]
`gitkraken-pro.sh` has been dropped. All rebuild code was been moved to `PKGBUILD`
