### ISSUE TITLE
Problem with gitcracken-v0.3.7

### ISSUE THREAD

**Issue by vanbwodonk** [KillWolfVlad/GitKraken-Pro-AUR#6]
I found problem with gitcracken 0.3.7, i'm using ubuntu 16.04.
if i run > `node bin/gitcracken.ts patcher auto`
I get error like this,

```
import * as program from 'commander';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:605:28)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```
Is that really .ts extension? or i missing something?
But if i used 0.3.6 bin, with 0.3.7 src it success to patch gitkraken 3.3.1.

**Comment by KillWolfVlad** [comment]
Please, follow `GitCracken` README

- `yarn install`
- `node dist/bin/gitcracken.js` --help for more usage information

`postinstall` hook should be invoked automatically (you can invoke it manually `yarn run build`)

> Is that really .ts extension? or i missing something?

[TypeScript](https://en.wikipedia.org/wiki/TypeScript)

> But if i used 0.3.6 bin, with 0.3.7 src it success to patch gitkraken 3.3.1.

I don't understand you. Can you paste `tree` output?

**Comment by vanbwodonk** [comment]
>  I don't understand you. Can you paste tree output?

I Just copy paste 0.3.6 bin folder and replace 0.3.7 bin folder. Then run
`node bin/gitcracken.ts patcher auto`
i got massage patching done, and got gitkraken pro

> Please, follow GitCracken README
> yarn install

Ops, missing 1 step.
I'm sorry inexperienced with nodejs before, cz 0.3.6 very easy to do patching.
now worked as always !! thx.

```
• Description: GitKraken utils for non-commercial use
• Version: 0.3.7
• Author: KillWolfVlad
• License: GPL-3.0
• Home Page: https://github.com/KillWolfVlad/GitKraken-Pro-AUR

==> 📦 Backup /usr/share/gitkraken/resources/app.asar ➔ /usr/share/gitkraken/resources/app.asar.1512971837181.backup
==> 🔓 Unpack /usr/share/gitkraken/resources/app.asar ➔ /usr/share/gitkraken/resources/app
==> 🔨 Patch /usr/share/gitkraken/resources/app with pro feature
==> 🔒 Pack /usr/share/gitkraken/resources/app ➔ /usr/share/gitkraken/resources/app.asar
==> 🔥 Remove /usr/share/gitkraken/resources/app
==> 👌 Patching done!
```
