### ISSUE TITLE
I am not able to install the gitcracken module

### ISSUE THREAD

**Issue by JavaMatia** [KillWolfVlad/GitKraken-Pro-AUR#7]
I decrypted the file and open and read it, and the only instructions about installing the script were "yarn install". I tried the find the dependencies file in this repo, and it the file, but couldn't find a thing. I usually have no problems doing these kinds of things, but I can't find any clue. Any help?
Thanks

**Comment by KillWolfVlad** [comment]
To launch `GitCracken` you should install

- [Node.js](https://nodejs.org)
- [yarn](https://yarnpkg.com)

**Comment by JavaMatia** [comment]
Already installed, I am a web developer. But from where do I ran the yarn command?

**Comment by KillWolfVlad** [comment]
From directory with `package.json`

**Comment by JavaMatia** [comment]
WHERE is it? It is neither in your repository nor in the .xz archive I downloaded.

**Comment by KillWolfVlad** [comment]
Can you start from scratch?

```bash
$ curl https://pastebin.com/raw/HwnX4vG2 -o GitCracken-v0.3.9.tar.xz.txt
$ base64 -d GitCracken-v0.3.9.tar.xz.txt > GitCracken-v0.3.9.tar.xz
$ tar xf GitCracken-v0.3.9.tar.xz
$ cd GitCracken
$ yarn install
$ node dist/bin/gitcracken.js --help
```

**Comment by JavaMatia** [comment]
A. Thank you for the quick replies.
B. I am using Windows 10, so curl is not available. 
C. I copied the base64 code and decoded it online, and it started downloading the decoded.xz archive. Inside this archive I found a file called decoded containing information including yarn install

**Comment by KillWolfVlad** [comment]
Happy to help!
