### ISSUE TITLE
Different patch to make gitkraken pro

### ISSUE THREAD

**Issue by KoolimRezah** [KillWolfVlad/GitKraken-Pro-AUR#8]
GitCracken didn't work for me. I looked at what the patch does and it looks kinda weird. Not sure what happens there.
Instead, I looked at how gitkraken checks if it is PRO and there is a function called getIsPro that returns true or false based on a bunch of stuff. I changed that function to always return true.

I think that is a better patch to make gitkraken PRO and you should look into changing it.

**Comment by KillWolfVlad** [comment]
Can you answer these questions?

1) Your OS
2) GitCracken version
3) GitKraken version

**Comment by KillWolfVlad** [comment]
4. Node.js version
5. yarn version

**Comment by KillWolfVlad** [comment]
> getIsPro that returns true or false based on a bunch of stuff. I changed that function to always return true.

I changed this function in the previous release. But one change was not enough. Better patch server response on [/api/phone-home](https://github.com/KillWolfVlad/GitKraken-Enterprise-Server/blob/master/docs/api/phone-home.md) request.

P.S. Can you paste patch file here?

**Comment by KoolimRezah** [comment]
1. windows 10
2. Not sure where it says the version, I used the release url and it says: 0.3.9
3. 3.4.1
4. 8.10
5. 0.10

In case it was not clear from the "issue", that patch was applied successfully. Its just that the patch didn't make GitKraken PRO.

**Comment by KillWolfVlad** [comment]
> Its just that the patch didn't make GitKraken PRO.
> that patch was applied successfully

Maybe patch was applied incorrectly?

Can you attach patched 
`~/AppData/Local/gitkraken/resources/app-3.4.1/src/js/actions/RegistrationActions.js` file?

P.S. yarn version is too old, actual is v1.5.1

**Comment by KillWolfVlad** [comment]
Did you use the trial Pro?

Patch looks correct. Maybe you should reinstall GitKraken, apply patch again and try activate GitKraken using other account. After patch you should unlock all Pro features (exclude Glo) as well.

The best way - reproduce this issue in chroot e.g. VirtualBox (and use other account).

**Comment by KoolimRezah** [comment]
Thank you for the incredibly quick response.

I installed it on a different machine and it worked, but it didn't work on an offline machine(that has never registered. May be that is the cause?)
Getting the PRO isn't a major issue since I just changed getIsPro in AppSelector.js(line 75)
I just wanted to let you know about this other way and wasn't sure how to contact you.

If you have an email and we can discuss there, that would be a better platform for me.
I don't check github regularly.

**Comment by KillWolfVlad** [comment]
> but it didn't work on an offline machine(that has never registered. May be that is the cause?)

You must have internet connection to activate GitKraken.

> Getting the PRO isn't a major issue since I just changed getIsPro in AppSelector.js(line 75)

I will try it in future release.

> If you have an email and we can discuss there, that would be a better platform for me.

I don't check email regularly. You can contact with me via [GitHub or VK](https://github.com/KillWolfVlad/GitKraken-Pro-AUR#need-help-or-you-want-help)

**Comment by KillWolfVlad** [comment]
> Getting the PRO isn't a major issue since I just changed getIsPro in AppSelector.js(line 75)

This changes don't unlock all PRO features.

@KoolimRezah Can you create normal `*.diff` file (see GitCracken v0.3.10 changelog)?

But currently I close this issue.
